name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
        stack-version: '2.1.0'        
    - name: Build
      run: |
        stack init
        stack install
    - name: Run tests
      run: stack test
